# Generated by Django 3.2.8 on 2021-11-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('a', 'Clothing'), ('b', 'Furniture'), ('c', 'Electronics'), ('d', 'Miscellaneous'), ('e', 'Kitchen'), ('f', 'None')], default='None', max_length=1),
        ),
    ]
